### ISSUE TITLE
TypeError: can't pickle NotImplementedType objects on sklearn.metrics.make_scorer and FeatureUnion

### ISSUE THREAD

**Issue by data-steve** [dask/dask-searchcv#56]
I'm implementing a gridsearch on pipeline where the classifiers are swapped out. Using sklearn gridsearch, it worked ok.  

```
gridSearch_features = GridSearchCV(estimator=pipeline,
            param_grid=feature_parameters,
            scoring =  'neg_log_loss', 
            n_jobs=-1, refit=True)

from sklearn.metrics import make_scorer,  brier_score_loss
brier = make_scorer(brier_score_loss, greater_is_better=False)

gridSearch_features = GridSearchCV(estimator=pipeline,
            param_grid=feature_parameters,
            scoring =  brier, 
            n_jobs=-1, refit=True)
```

I tried to drop in dask.GridSearchCV and got an error that I believe is connected to make_scorer object:

```Traceback (most recent call last):
  File "hal_crossval_search_features_multi.py", line 397, in <module>
    gridSearch_features_model = gridSearch_features.fit(train_x,train_y)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/model_selection.py", line 801, in fit
    out = scheduler(dsk, keys, num_workers=n_jobs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/methods.py", line 216, in fit_transform
    est = set_params(est, fields, params)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/methods.py", line 182, in set_params
    est = copy_estimator(est)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/utils.py", line 65, in copy_estimator
    return copy.deepcopy(est)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
TypeError: can't pickle NotImplementedType objects
```

**Comment by data-steve** [comment]
I also get a similar error when I try to grid search over a feature Union pipeline that calls in deeper than level one in the pipeline for example below:

```
feature_parameters = {
        'features__title__union__tfidf__min_df' : [1e-05, 1e-03, ] }
```

```
Traceback (most recent call last):
  File "hal_crossval_search_features_multi.py", line 404, in <module>
    gridSearch_features_model = gridSearch_features.fit(train_x,train_y)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/model_selection.py", line 801, in fit
    out = scheduler(dsk, keys, num_workers=n_jobs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/methods.py", line 216, in fit_transform
    est = set_params(est, fields, params)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/methods.py", line 182, in set_params
    est = copy_estimator(est)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask_searchcv/utils.py", line 65, in copy_estimator
    return copy.deepcopy(est)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/mnt/var/lib/anaconda2/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
TypeError: can't pickle NotImplementedType objects```

**Comment by jcrist** [comment]
Thanks for the issue report. Can you provide a [minimal example](https://stackoverflow.com/help/mcve) that reproduces this issue? This should be something I can just call `python test.py` on and get the error.

**Comment by data-steve** [comment]
yeah, its a bit of code so was trying to get away with as little as possible, my bad.

I'm currently running it on py27. sklearn 0.18.0 defines the dependency versions.

Another place I saw a similar deepcopy error even with sklearn GridSearchCV was in my `RegexCounter` custom transformer when I pre-compiled the regex. It didn't like that,  so I've left the code there in case you want to see that behavior too.

To do:
1. define path to test3.csv 

Possible sources of deepcopy error:
1. comment out Dask-GridSearch and uncomment Sklearn-GridSearch, this gets at a basic problem with GridSearch-ing over the feature_parameter settings when the features are below first-level in pipeline, like in a FeatureUnion
2. can also swap in `brier` scorer on the GridSearch line for `scoring=` param.
3. can change the `re.compile` part of `RegexCounter` custom transformer to see another even, which I think also occurs for SKlearn GridSearch

Solving #1 seems like pre-req to solving the others.

test.py below
```
#! /usr/bin/python
from __future__ import print_function




####################################
# Create custom_transforms
####################################
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import  TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import  AdaBoostClassifier, RandomForestClassifier
import nltk
import pandas as pd
import re
import numpy as np


from sklearn.base import BaseEstimator,TransformerMixin



class SeriesSelector(BaseEstimator, TransformerMixin):
    """ A feature selector for scikit-learn's Pipeline class that returns
        specified columns as a numpy nested array from a nested numpy array.
    """

    def __init__(self, key):
        import pandas as pd
        self.pd = pd
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, X):
        print(self.key)
        return X[self.key]


class RegexCounter(BaseEstimator, TransformerMixin):

    """
    Count number of items fitting certain regex
    """

    def __init__(self, regex, percent=False):
        import pandas as pd
        import re
        self.pd = pd
        self.re = re
        self.regex = regex
        # can't do precompiled object here because
        # deepcopy process later in pipeline didn't have
        # a deepcopy method to pass on a compiled regex
        # bec it expected a string
        # # self.regex = re.compile(regex)
        self.percent = percent


    def fit(self, x, y=None):
        return self

    def transform(self, X):
        #X = X.reshape(-1,1)
        print("RegexCounter")
        if isinstance(X,self.pd.DataFrame):
            X = X.unstack()
        cnts = X.str.findall(self.regex).apply(len).astype(float)
        if self.percent:
            cnts = cnts/X.str.len()
        return self.pd.DataFrame(cnts)




from sklearn.linear_model import SGDClassifier, LogisticRegression
# from sklearn.model_selection import GridSearchCV
from dask_searchcv import GridSearchCV


# CapCounter = RegexCounter(regex=r'[A-Z]', percent=True)
PuncCounter = RegexCounter(regex=r'[^\w\s]', percent=True)

def main():
    import os
    ec2_path = os.path.expanduser("~")
    train_rolled = pd.read_csv(ec2_path + '/test.csv')
    print(train_rolled.columns)

    x_vars = ['character','phrase']
    train_x = train_rolled[x_vars]
    train_y = train_rolled.Target

    phrase_features_multi = Pipeline([('selector', SeriesSelector(key='phrase')),
                        ('union',  FeatureUnion([
                            # ('cap', CapCounter),
                            ('punct', PuncCounter),
                            ('tfidf', TfidfVectorizer(min_df = 0.1, max_df = 0.8, stop_words = 'english', )) #tokenizer= remove_nums_longword_tokenizer
                            #,('print', ShapePrinter())
                            ]) ),
                        # ('print', ShapePrinter())

                        ])

    pipeline = Pipeline([
        # Use FeatureUnion to combine the features
        ('phrase', phrase_features_multi),
        ('scaler', StandardScaler(with_mean=False)),
        ('LG', LogisticRegression())
    ])

    feature_parameters = {
            'phrase__union__tfidf__min_df' : [0.1,1], #ngram_range,
                  }

    from sklearn.metrics import accuracy_score
    from sklearn.metrics import make_scorer, brier_score_loss
    brier = make_scorer(brier_score_loss, greater_is_better=False)


    gridSearch_features = GridSearchCV(estimator=pipeline,
        param_grid=feature_parameters, cv=2,
        scoring =  'neg_log_loss', # brier,  
        n_jobs=-1, refit=True)
    # start_model_time=time()
    gridSearch_features_model = gridSearch_features.fit(train_x,train_y)
    # end_model_time = time()

    print(gridSearch_features)
    print(gridSearch_features_model)


if __name__ == "__main__":
    main()
```

Here's data for test.csv:
```
id_x,phrase,character,Target
1,hi ho ,Seven Dwarfs,1
2,I eat my spinach,Popeye,0
3,baterang, Batman,1
4,spidey-sense, Spiderman,0
```

**Comment by TomAugspurger** [comment]
Any reason you're attaching the modules as `self.pd = pd`? That's what's causing the errors, since modules aren't picklable (by default). Removing all those fixes the error.

**Comment by data-steve** [comment]
That's the recommended behavior for custom transforms and distributed models. 

~ Steve

Sent via telepathy

**Comment by data-steve** [comment]
Or if it's not please disabuse me. 

~ Steve

Sent via telepathy

**Comment by TomAugspurger** [comment]
> That's the recommended behavior for custom transforms and distributed models.

I've never seen that, and can't imagine why it would be the recommendation, but I may be missing something.

**Comment by data-steve** [comment]
I defer to your experience. Thanks a ton!
